### ISSUE TITLE
[iOS] Failed to set requested image library.

### ISSUE THREAD

**Issue by tyleratblowfish** [Unity-Technologies/arfoundation-samples#124]
Hey, how's it going. Is this the right place to post this.

I'm having an issue for IOS that Logs the following error message in-game:
`InvalidOperationException: Failed to set requested image library 'ReferenceImageLibrary' on ARKit - there is no matching group, or the resource group does not contain any reference images.`

The error message above comes when building on mac through jenkins.

If I try to build it on my local windows 10 machine I get an error message:
`DirectoryNotFoundException: Destination directory not found: D:\Users\TylerOBrien\Documents\**************\Build\iPhone\Dev\NewUnityProject_v0.1.0.0_9cd61b9\Unity-iPhone\ARReferenceImages.xcassets\ReferenceImageLibrary_1E7D380C-02DA-4810-B8DF-EB68D0A83D1D.arresourcegroup\Dragons_4339fb123de84bc08c045314da4b338c.arreferenceimage
System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
UnityEditor.XR.ARKit.ARReferenceImage.Write (System.String pathToResourceGroup) (at Library/PackageCache/com.unity.xr.arkit@2.1.0-preview.3/Editor/ARReferenceImage.cs:62)
UnityEditor.XR.ARKit.ARResourceGroup.Write (System.String pathToAssetCatalog) (at Library/PackageCache/com.unity.xr.arkit@2.1.0-preview.3/Editor/ARResourceGroup.cs:48)
UnityEditor.XR.ARKit.XcodeAssetCatalog.WriteAndAddToPBXProject (UnityEditor.iOS.Xcode.PBXProject project, System.String pathToBuiltProject) (at Library/PackageCache/com.unity.xr.arkit@2.1.0-preview.3/Editor/XcodeAssetCatalog.cs:54)
UnityEditor.XR.ARKit.ARKitReferenceImageLibraryBuildProcessor+Postprocessor.OnPostprocessBuild (UnityEditor.Build.Reporting.BuildReport report) (at Library/PackageCache/com.unity.xr.arkit@2.1.0-preview.3/Editor/ARKitReferenceImageLibraryBuildProcessor.cs:120)
UnityEditor.Build.BuildPipelineInterfaces+<OnBuildPostProcess>c__AnonStorey2.<>m__1 (UnityEditor.Build.IPostprocessBuildWithReport bpp) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:398)
UnityEditor.Build.BuildPipelineInterfaces.InvokeCallbackInterfacesPair[T1,T2] (System.Collections.Generic.List`1[T] oneInterfaces, System.Action`1[T] invocationOne, System.Collections.Generic.List`1[T] twoInterfaces, System.Action`1[T] invocationTwo, System.Boolean exitOnFailure) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:356)
UnityEditor.BuildPipeline:BuildPlayer(BuildPlayerOptions)`

I think the problem on my local machine is that the file path is too long although I get the same error message building to the desktop.

Thanks for reading!

**Comment by tyleratblowfish** [comment]
If you want any more details, just let me know.

**Comment by tyleratblowfish** [comment]
Oh also I'm using:
Unity 2018.2.20f1 (64-bit)
AR Foundation 1.5.0-preview.2
ARCore 2.1.0-preview.4
ARKit 2.1.0-preview.3

**Comment by tdmowrer** [comment]
Is  ```D:\Users\TylerOBrien\Documents\**************\``` really part of the path, or did you change that for privacy reasons? Asterisks cannot form a valid pathname in Windows, so something is up.

> Oh also I'm using:
> Unity 2018.2.20f1 (64-bit)

ARFoundation 1.5 is not compatible with Unity 2018.2. Did you mean 2018.3 (or something else)?

> I'm having an issue for IOS that Logs the following error message in-game:
> ```InvalidOperationException: Failed to set requested image library 'ReferenceImageLibrary' on ARKit - there is no matching group, or the resource group does not contain any reference images.```

Create this script in your project:
```csharp
using System.Text;
using UnityEngine;
using UnityEngine.XR.ARSubsystems;
using UnityEditor;

static class ListReferenceImageLibraries
{
    [MenuItem("ARFoundation/List Image Libraries")]
    static void ListLibraries()
    {
        var sb = new StringBuilder();
        var guids = AssetDatabase.FindAssets("t:XRReferenceImageLibrary");
        if (guids.Length == 0)
        {
            sb.Append("No reference image libraries found.");
        }
        else
        {
            sb.Append($"Found {guids.Length} reference image libraries:");
            foreach (var guid in guids)
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                sb.Append($"\n\t{path}");
            }
        }

        Debug.Log(sb.ToString());
    }
}
```
And then, please click "ARFoundation > List Image Libraries" and post the console output here.

**Comment by tyleratblowfish** [comment]
> or did you change that for privacy reasons? Asterisks cannot form a valid pathname in Windows, so something is up.

Yeah, just for privacy reasons


> ARFoundation 1.5 is not compatible with Unity 2018.2. Did you mean 2018.3 (or something else)?

Ah, yep sorry it's Unity 2018.3.11f1 (64-bit)


> And then, please click "ARFoundation > List Image Libraries" and post the console output here.
```
Found 1 reference image libraries:
	Assets/Prototype/Data/ReferenceImageLibrary.asset
UnityEngine.Debug:Log(Object)
ListReferenceImageLibraries:ListLibraries() (at Assets/Prototype/ListReferenceImages.cs:27)
```
Thanks again!

**Comment by tdmowrer** [comment]
Okay, everything looks good so far.

In the generated Xcode project, you should see an asset catalog like this:
![Screen Shot 2019-05-21 at 4 37 49 PM](https://user-images.githubusercontent.com/4934281/58137373-de131d80-7be6-11e9-8a15-fdc063d0f484.png)

Do you have that?

**Comment by tyleratblowfish** [comment]
> Do you have that?
![image](https://user-images.githubusercontent.com/50857860/58137539-f67e4900-7c75-11e9-81da-17597172f866.png)

I tried shortening down the names and building in highest folder I could. It got a bit further this time.

It's getting to "D:\A\Unity-iPhone\ARReferenceImages.xcassets\R_1E7D380C-02DA-4810-B8DF-EB68D0A83D1D.arresourcegroup" and it threw:
```
DirectoryNotFoundException: Could not find a part of the path "D:\A\Unity-iPhone\ARReferenceImages.xcassets\R_1E7D380C-02DA-4810-B8DF-EB68D0A83D1D.arresourcegroup\D_4339fb123de84bc08c045314da4b338c.arreferenceimage\Contents.json".
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options, System.String msgPath, System.Boolean bFromProxy, System.Boolean useLongPath, System.Boolean checkHost) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
(wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions,string,bool,bool,bool)
System.IO.StreamWriter.CreateFile (System.String path, System.Boolean append, System.Boolean checkHost) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.IO.StreamWriter..ctor (System.String path, System.Boolean append, System.Text.Encoding encoding, System.Int32 bufferSize, System.Boolean checkHost) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.IO.StreamWriter..ctor (System.String path, System.Boolean append, System.Text.Encoding encoding, System.Int32 bufferSize) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.IO.StreamWriter..ctor (System.String path, System.Boolean append, System.Text.Encoding encoding) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
(wrapper remoting-invoke-with-check) System.IO.StreamWriter..ctor(string,bool,System.Text.Encoding)
System.IO.File.WriteAllText (System.String path, System.String contents, System.Text.Encoding encoding) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.IO.File.WriteAllText (System.String path, System.String contents) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
UnityEditor.XR.ARKit.ARReferenceImage.Write (System.String pathToResourceGroup) (at Library/PackageCache/com.unity.xr.arkit@2.1.0-preview.3/Editor/ARReferenceImage.cs:116)
UnityEditor.XR.ARKit.ARResourceGroup.Write (System.String pathToAssetCatalog) (at Library/PackageCache/com.unity.xr.arkit@2.1.0-preview.3/Editor/ARResourceGroup.cs:48)
UnityEditor.XR.ARKit.XcodeAssetCatalog.WriteAndAddToPBXProject (UnityEditor.iOS.Xcode.PBXProject project, System.String pathToBuiltProject) (at Library/PackageCache/com.unity.xr.arkit@2.1.0-preview.3/Editor/XcodeAssetCatalog.cs:54)
UnityEditor.XR.ARKit.ARKitReferenceImageLibraryBuildProcessor+Postprocessor.OnPostprocessBuild (UnityEditor.Build.Reporting.BuildReport report) (at Library/PackageCache/com.unity.xr.arkit@2.1.0-preview.3/Editor/ARKitReferenceImageLibraryBuildProcessor.cs:120)
UnityEditor.Build.BuildPipelineInterfaces+<OnBuildPostProcess>c__AnonStorey2.<>m__1 (UnityEditor.Build.IPostprocessBuildWithReport bpp) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:398)
UnityEditor.Build.BuildPipelineInterfaces.InvokeCallbackInterfacesPair[T1,T2] (System.Collections.Generic.List`1[T] oneInterfaces, System.Action`1[T] invocationOne, System.Collections.Generic.List`1[T] twoInterfaces, System.Action`1[T] invocationTwo, System.Boolean exitOnFailure) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:356)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

**Comment by tdmowrer** [comment]
Do you have a Mac you could try building on locally?

**Comment by tyleratblowfish** [comment]
Sorry, I've got the build machines I can launch and I can log out of them. But I wouldn't be able to remote into them.

**Comment by tdmowrer** [comment]
Okay, so looks like 2 potential issues:
1. The reference image library cannot be found when the iOS app is generated on a Mac on a build farm (for unknown reasons).
1. The reference image library cannot be built on your Windows machine.

I'm going to try to reproduce 2 here. Are you running the samples from this repo or something else?

**Comment by tyleratblowfish** [comment]
Another project. I'll see if I can reproduce on the samples though.

Here's the asset file if that helps.
```
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!114 &11400000
MonoBehaviour:
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  m_GameObject: {fileID: 0}
  m_Enabled: 1
  m_EditorHideFlags: 0
  m_Script: {fileID: 11500000, guid: 848409ee8ba454f42a5ddff137688a27, type: 3}
  m_Name: R
  m_EditorClassIdentifier: 
  m_GuidLow: 5192653506195830796
  m_GuidHigh: 2107025813746212792
  m_Images:
  - m_SerializedGuid:
      m_GuidLow: 5458430816142621458
      m_GuidHigh: 10102501789138093196
    m_SerializedTextureGuid:
      m_GuidLow: 5112795345619770257
      m_GuidHigh: 14944890589251925242
    m_Size: {x: 0.11938, y: 0.11938}
    m_SpecifySize: 1
    m_Name: D
    m_Texture: {fileID: 0}
  - m_SerializedGuid:
      m_GuidLow: 5577293682293084323
      m_GuidHigh: 17243153780304814232
    m_SerializedTextureGuid:
      m_GuidLow: 13593181031647830292
      m_GuidHigh: 12347153711879132843
    m_Size: {x: 0.071628, y: 0.076161414}
    m_SpecifySize: 1
    m_Name: B
    m_Texture: {fileID: 0}
  - m_SerializedGuid:
      m_GuidLow: 4626899754980192547
      m_GuidHigh: 17643537715485360034
    m_SerializedTextureGuid:
      m_GuidLow: 3919465172838756505
      m_GuidHigh: 10503078617550048683
    m_Size: {x: 0.2159, y: 0.11520356}
    m_SpecifySize: 1
    m_Name: L
    m_Texture: {fileID: 0}
```
